### ISSUE TITLE
There is no mention about slack commands needed to be configured before running the example

### ISSUE THREAD

**Issue by a2glukhov** [MicrosoftDocs/bot-docs.ru-ru#2]
[Введите отзыв здесь]

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 97b7eb7d-843a-774e-3ee4-8f3126cfea20
* Version Independent ID: 5d501ffc-819f-0634-671c-13d432aa7f28
* Content: [Подключение бота к Slack (служба Azure Bot) - Bot Service](https://docs.microsoft.com/ru-ru/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs)
* Content Source: [articles/bot-service-channel-connect-slack.md](https://github.com/MicrosoftDocs/bot-docs.ru-ru/blob/live/articles/bot-service-channel-connect-slack.md)
* Service: **bot-service**
* GitHub Login: @JonathanFingold
* Microsoft Alias: **kamrani**

**Comment by srvbpigh** [comment]
Hello, @a2glukhov
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @a2glukhov, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/bot-docs/issues/1560. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
